package com.privoraa.ai.classification;

/** Safe-to-log deterministic signals. Values never contain prompt fragments. */
public enum ClassificationReason {
    CODE_KEYWORD_MATCH,
    STACK_TRACE_DETECTED,
    REPOSITORY_LANGUAGE_MATCH,
    ARCHITECTURE_LANGUAGE_MATCH,
    RESEARCH_LANGUAGE_MATCH,
    LEARNING_LANGUAGE_MATCH,
    DOCUMENT_LANGUAGE_MATCH,
    WRITING_LANGUAGE_MATCH,
    DATA_LANGUAGE_MATCH,
    AUTOMATION_LANGUAGE_MATCH,
    IMAGE_PRESENT,
    RAG_ENABLED,
    CURRENT_DATE_LANGUAGE,
    PRIVATE_MODE_SELECTED,
    EXPLICIT_LOCAL_ONLY_REQUEST,
    SENSITIVE_DATA_PATTERN,
    PERSONAL_CONTEXT_MATCH,
    LONG_PROMPT,
    LARGE_CONTEXT,
    MODE_BIAS,
    AMBIGUOUS_REQUEST,
    FALLBACK_CLASSIFICATION
}
